name: 'PR Backporter'
description: 'Backports a pull request to a branch using a comment'
inputs:
  auth_token:
    description: 'The token used to authenticate to GitHub.'
runs:
  using: 'node12'
  main: 'index.js'
