name: Backport PR to branch
on:
  issue_comment:
    types: [created]

jobs:
  backport:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/backport to')
    runs-on: ubuntu-20.04
    steps:
    - name: Get target branch
      id: targetbranch
      env:
        BACKPORT_TRIGGER_BODY: ${{ github.event.comment.body }}
      run: |
        # extract the target branch name containing these characters: a-z, A-Z, digits, forward slash, dot, hyphen, underscore
        BRANCHNAME=$(echo '{}' | jq --raw-output 'env.BACKPORT_TRIGGER_BODY | match("\\/backport to ([a-zA-Z\\d\\/\\.\\-\\_]+)").captures[0].string')
        echo "Backport target branch: $BRANCHNAME"
        echo "::set-output name=branchname::$BRANCHNAME"
    - name: Checkout repo at target branch
      uses: actions/checkout@v2
      with:
         ref: ${{ steps.targetbranch.outputs.branchname }}
    - name: Apply backport patch, push and open PR
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Download backport patch
        curl -sSL "${{ github.event.issue.pull_request.patch_url }}" --output changes.patch

        # configure git
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

        # create temporary backport branch
        temp_branch="backport/pr-${{ github.event.issue.number }}-to-${{ steps.targetbranch.outputs.branchname }}"
        git checkout -b $temp_branch

        # apply the patch and push to origin
        git am changes.patch --3way --ignore-whitespace --keep-non-patch
        git push --force --set-upstream origin HEAD:$temp_branch
        
        # open PR
        hub pull-request -b ${{ steps.targetbranch.outputs.branchname }} -m "Backport PR"
