name: Backport PR to branch
on:
  issue_comment:
    types: [created]

jobs:
  backport:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/backport to')
    runs-on: ubuntu-latest
    steps:
    - name: $github
      run: echo "$GITHUB_CONTEXT"
      env:
       GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Get target branch
      id: targetbranch
      env:
        BACKPORT_TRIGGER_BODY: ${{ toJson(github.event.comment.body) }}
      run: echo "::set-output name=branchname::$(echo $BACKPORT_TRIGGER_BODY | sed 's/\/backport to (\S*)/\1/g')"
    - name: Checkout repo at target branch
      uses: actions/checkout@v2
      with:
         ref: ${{ steps.targetbranch.outputs.branchname }}
