name: Backport PR to branch
on:
  issue_comment:
    types: [created]

jobs:
  backport:
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/backport to')
    runs-on: ubuntu-latest
    steps:
    - name: $github
      run: echo "$GITHUB_CONTEXT"
      env:
       GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Get target branch
      id: targetbranch
      env:
        BACKPORT_TRIGGER_BODY: ${{ github.event.comment.body }}
      run: |
        # extract the target branch name containing these characters: a-z, A-Z, digits, forward slash, dot, hyphen, underscore
        BRANCHNAME=$(echo '{}' | jq --raw-output 'env.BACKPORT_TRIGGER_BODY | match("\\/backport to ([a-zA-Z\\d\\/\\.\\-\\_]+)").captures[0].string')
        echo "Backport target branch: $BRANCHNAME"
        echo "::set-output name=branchname::$BRANCHNAME"
    - name: Checkout repo at target branch
      uses: actions/checkout@v2
      with:
         ref: ${{ steps.targetbranch.outputs.branchname }}
    - name: Download backport patch
      run: curl -sSL "${{ github.event.issue.pull_request.patch_url }}" --output changes.patch
    - name: Apply backport patch
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        temp_branch="backport-pr-${{ github.event.issue.number }}-to-${{ steps.targetbranch.outputs.branchname }}"
        git checkout -b $temp_branch

        echo "Applying git patch:" >> output.log
        if [[ git am changes.patch --3way --ignore-whitespace --keep-non-patch >> output.log 2>&1 ]]; then
          echo Success
        fi
    - name: Print output
      run: cat output.log || true
